### ISSUE TITLE
localhost:5001 not responding

### ISSUE THREAD

**Issue by trogne** [dockersamples/example-voting-app#184]
Hi,

The app work on port on localhost:5000, but I have nothing at localhost:5001.

What could be wrong ?

I get this in docker-compuse up log : 

result_1  | [nodemon] 2.0.6
result_1  | [nodemon] to restart at any time, enter `rs`
result_1  | [nodemon] watching path(s): *.*
result_1  | [nodemon] watching extensions: js,mjs,json
result_1  | [nodemon] starting `node server.js`
result_1  | /app/server.js:26
result_1  | var pool = new pg.Pool({
result_1  |            ^
result_1  | 
result_1  | TypeError: pg.Pool is not a constructor
result_1  |     at Object.<anonymous> (/app/server.js:26:12)
result_1  |     at Module._compile (module.js:643:30)
result_1  |     at Object.Module._extensions..js (module.js:654:10)
result_1  |     at Module.load (module.js:556:32)
result_1  |     at tryModuleLoad (module.js:499:12)
result_1  |     at Function.Module._load (module.js:491:3)
result_1  |     at Function.Module.runMain (module.js:684:10)
result_1  |     at startup (bootstrap_node.js:187:16)
result_1  |     at bootstrap_node.js:608:3
result_1  | [nodemon] app crashed - waiting for file changes before starting...

**Comment by trogne** [comment]
Closed cause it works after a restart.
